# Generated by Django 3.2.14 on 2022-07-23 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 11, 54, 41, 359410, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
